"""Brandfetch logo service.

This module resolves logo URLs using Brandfetch search endpoint and caches
the resulting icon URL by ticker.
"""

import json
import logging
import os
import re
import hashlib
import mimetypes
import tempfile
from datetime import datetime
from typing import Optional
from urllib.parse import quote, urlparse

import requests

from app.services.finnhub_service import finnhub_service

logger = logging.getLogger(__name__)


class LogoDownloadTransientError(Exception):
    """Raised when logo download fails transiently and should not null-cache."""

CACHE_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'cache')
LOGO_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'static', 'logos')
os.makedirs(CACHE_DIR, exist_ok=True)
os.makedirs(LOGO_DIR, exist_ok=True)

_LOGO_CACHE_TTL = 86400
MAX_LOGO_BYTES = 5 * 1024 * 1024
_LOGO_CACHE: dict[str, tuple[Optional[str], float]] = {}
_CURATED_LOGO_QUERIES: dict[str, list[str]] = {
    "EQT.ST": ["eqtpartners.com", "EQT Group"],
    "INVE-B.ST": ["investorab.com", "Investor AB"],
    "VOLV-B.ST": ["volvogroup.com", "Volvo Group"],
    "RIO.AX": ["riotinto.com", "Rio Tinto"],
    "OR.PA": ["loreal.com", "L'Oreal"],
}

_session: Optional[requests.Session] = None
_ALLOWED_REMOTE_LOGO_HOSTS = {
    'cdn.brandfetch.io',
    'logo.clearbit.com',
    'www.google.com',
    'icons.duckduckgo.com',
}
_LEGACY_BRANDFETCH_HOSTS = {
    'cdn.brandfetch.io',
}


def _resolve_cache_path(filename: str) -> str:
    """
    Resolve a filename to an absolute path confined inside the module cache directory.
    
    Parameters:
        filename (str): A cache filename or relative path; may include subdirectories.
    
    Returns:
        str: Absolute path to the resolved cache file inside the module cache directory.
    
    Raises:
        ValueError: If the resolved path is outside the configured cache directory.
    """
    cache_dir_abs = os.path.abspath(CACHE_DIR)
    filepath = os.path.abspath(os.path.join(cache_dir_abs, filename))
    if filepath != cache_dir_abs and not filepath.startswith(f"{cache_dir_abs}{os.sep}"):
        raise ValueError(f"Invalid cache path outside cache directory: {filename}")
    return filepath


def _safe_logo_cache_filename(ticker_upper: str) -> str:
    """
    Generate a deterministic, filesystem-safe cache filename for an uppercased ticker.
    
    Parameters:
        ticker_upper (str): Uppercased ticker used to derive the filename.
    
    Returns:
        filename (str): Versioned JSON filename derived from the SHA-256 digest (first 24 hex chars) of the ticker, e.g. "brandfetch_logo_v2_<digest>.json".
    """
    digest = hashlib.sha256(ticker_upper.encode('utf-8')).hexdigest()[:24]
    return f"brandfetch_logo_v2_{digest}.json"


def _safe_logo_asset_filename(ticker_upper: str, source: str, extension: str) -> str:
    """
    Create a deterministic, filesystem-safe filename for a downloaded logo asset.
    
    Parameters:
        ticker_upper (str): Uppercase ticker symbol used as part of the identity for the asset.
        source (str): Source identifier or URL used to distinguish different assets for the same ticker.
        extension (str): File extension (with or without leading dot); will be normalized to start with a dot.
    
    Returns:
        filename (str): A filename in the form "logo_<digest><extension>" where <digest> is a stable short hash derived from `ticker_upper` and `source`.
    """
    digest = hashlib.sha256(f"{ticker_upper}:{source}".encode('utf-8')).hexdigest()[:24]
    sanitized_extension = extension if extension.startswith('.') else f'.{extension}'
    return f"logo_{digest}{sanitized_extension}"


def _get_session() -> requests.Session:
    """
    Provide a configured, shared requests Session for HTTP requests.
    
    Returns:
        requests.Session: The module-level singleton Session with default headers set (`User-Agent`, `Accept`, `Accept-Language`, `Connection`).
    """
    global _session
    if _session is None:
        _session = requests.Session()
        _session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.9',
            'Connection': 'keep-alive',
        })
    return _session


def _load_file_cache(filename: str) -> tuple[bool, Optional[str]]:
    """
    Load a cached logo value from a file if the cache entry exists and is still valid.
    
    Attempts to resolve and read the JSON cache file for `filename`. Validates the entry's TTL using the file's `timestamp` and `ttl` (falls back to the module default TTL). Recognizes an explicit cached null via the `is_null` flag.
    
    Parameters:
        filename (str): Cache filename (relative name previously generated by the module).
    
    Returns:
        tuple[bool, Optional[str]]: A pair where the first element is `True` if a valid cache entry was found (including an explicit null), `False` otherwise. The second element is the cached string value when present, or `None` if the cache recorded a null or no valid entry exists.
    
    Notes:
        On error (file read/parse/validation), the function logs a warning and returns `(False, None)`.
    """
    try:
        filepath = _resolve_cache_path(filename)
        if not os.path.exists(filepath):
            return False, None
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        if datetime.now().timestamp() - data.get('timestamp', 0) >= data.get('ttl', _LOGO_CACHE_TTL):
            return False, None

        if data.get('is_null') is True:
            return True, None

        if 'value' in data:
            return True, data.get('value')
    except Exception as exc:
        logger.warning(f"Failed to load cache file {filename}: {exc}")

    return False, None


def _save_file_cache(filename: str, value: Optional[str], ttl: int = _LOGO_CACHE_TTL) -> None:
    """
    Write a cache file for a ticker-resolved logo value.
    
    Creates or overwrites the cache JSON file identified by `filename` (resolved into the module cache directory) and records `value` (string URL or `None`), an `is_null` flag, the current timestamp, and the `ttl` (time-to-live in seconds). On failure the function logs a warning and returns without raising.
    
    Parameters:
        filename (str): Cache filename (resolved to the module cache directory).
        value (Optional[str]): Cached value to store; use `None` to record a null result.
        ttl (int): Time-to-live for the cached entry in seconds.
    """
    try:
        filepath = _resolve_cache_path(filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump({
                'value': value,
                'is_null': value is None,
                'timestamp': datetime.now().timestamp(),
                'ttl': ttl,
            }, f)
    except Exception as exc:
        logger.warning(f"Failed to save cache file {filename}: {exc}")


class BrandfetchService:
    def _is_local_logo_url(self, value: Optional[str]) -> bool:
        """
        Determine whether a string is a public local logo path under /static/logos/.
        
        @returns `true` if `value` is a non-empty string that starts with "/static/logos/", `false` otherwise.
        """
        return bool(value and value.startswith('/static/logos/'))

    def _is_remote_logo_url(self, value: Optional[str]) -> bool:
        """
        Determine whether a value is an absolute HTTP(S) URL that includes a network location.
        
        Parameters:
            value (Optional[str]): The value to test; may be None or an empty string.
        
        Returns:
            True if the value is an HTTP or HTTPS URL with a netloc, False otherwise.
        """
        if not value:
            return False
        parsed = urlparse(value)
        return parsed.scheme in {'http', 'https'} and bool(parsed.netloc)

    def _is_allowed_remote_logo_url(self, value: str) -> bool:
        """
        Check whether a remote logo URL is allowed based on scheme and host.
        
        Parameters:
            value (str): The URL to validate.
        
        Returns:
            true if the URL uses `http` or `https` and its hostname is in the allowed hosts set, `false` otherwise.
        """
        parsed = urlparse(value)
        return parsed.scheme in {'http', 'https'} and parsed.netloc.lower() in _ALLOWED_REMOTE_LOGO_HOSTS

    def _is_legacy_remote_logo_url(self, value: str) -> bool:
        """
        Determine whether a URL points to a legacy Brandfetch host.
        
        Parameters:
            value (str): The URL to check.
        
        Returns:
            true if `value` is an `http` or `https` URL whose host is listed in the legacy Brandfetch hosts, false otherwise.
        """
        if not value:
            return False
        parsed = urlparse(value)
        return parsed.scheme in {'http', 'https'} and parsed.netloc.lower() in _LEGACY_BRANDFETCH_HOSTS

    def _logo_public_path(self, filename: str) -> str:
        """
        Constructs the public URL path for a stored logo asset.
        
        Parameters:
            filename (str): Filesystem-safe filename of the stored logo (basename only).
        
        Returns:
            str: Public path beginning with '/static/logos/' followed by the provided filename.
        """
        return f"/static/logos/{filename}"

    def _download_logo_to_local(self, logo_url: str, ticker: str) -> Optional[str]:
        """
        Download an allowed remote logo image, store it in the service's logo directory, and return its public path.
        
        Parameters:
            logo_url (str): Remote URL of the logo to download; must be an allowed host.
            ticker (str): Ticker symbol used to derive a deterministic local filename for the stored asset.
        
        Returns:
            Optional[str]: The public path to the stored logo asset (e.g., "/static/logos/<filename>") if the image was successfully downloaded and saved, `None` otherwise.
        """
        if not self._is_allowed_remote_logo_url(logo_url):
            return None

        session = _get_session()
        filepath: Optional[str] = None
        temp_path: Optional[str] = None
        response: Optional[requests.Response] = None
        try:
            response = session.get(logo_url, timeout=10, stream=True)

            redirect_chain = [redirect.url for redirect in response.history] + [response.url]
            if any(not self._is_allowed_remote_logo_url(url) for url in redirect_chain if url):
                return None

            if response.status_code in (204, 404, 410):
                return None
            if response.status_code == 429 or response.status_code >= 500:
                raise LogoDownloadTransientError(f"upstream status {response.status_code}")
            if response.status_code != 200:
                return None

            content_length = response.headers.get('Content-Length')
            if content_length:
                try:
                    if int(content_length) > MAX_LOGO_BYTES:
                        return None
                except ValueError:
                    pass

            content_type = (response.headers.get('Content-Type') or '').split(';', 1)[0].strip().lower()
            if not content_type.startswith('image/'):
                return None

            extension = mimetypes.guess_extension(content_type) or os.path.splitext(urlparse(logo_url).path)[1] or '.png'
            if extension == '.jpe':
                extension = '.jpg'

            filename = _safe_logo_asset_filename(ticker, logo_url, extension)
            filepath = os.path.join(LOGO_DIR, filename)
            fd, temp_path = tempfile.mkstemp(dir=LOGO_DIR, prefix='logo_tmp_', suffix=extension)
            bytes_written = 0
            with os.fdopen(fd, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    if not chunk:
                        continue
                    bytes_written += len(chunk)
                    if bytes_written > MAX_LOGO_BYTES:
                        raise OSError(f"Logo exceeds maximum size of {MAX_LOGO_BYTES} bytes")
                    f.write(chunk)

            os.replace(temp_path, filepath)
            temp_path = None

            return self._logo_public_path(filename)
        except requests.RequestException as exc:
            if temp_path and os.path.exists(temp_path):
                try:
                    os.remove(temp_path)
                except OSError:
                    pass
            logger.warning("Failed to persist logo for %s from %s: %s", ticker, logo_url, exc)
            raise LogoDownloadTransientError(str(exc)) from exc
        except OSError as exc:
            if temp_path and os.path.exists(temp_path):
                try:
                    os.remove(temp_path)
                except OSError:
                    pass
            logger.warning("Failed to persist logo for %s from %s: %s", ticker, logo_url, exc)
            raise LogoDownloadTransientError(str(exc)) from exc
        finally:
            if response is not None:
                response.close()

    def _domain_favicon_candidates(self, domain: str) -> list[str]:
        """
        Builds two favicon service URLs for a domain to use as favicon/logo fallbacks.
        
        Parameters:
            domain (str): Domain-like string (hostname, possibly including path/port); empty or whitespace returns an empty list.
        
        Returns:
            list[str]: A list containing two favicon candidate URLs (Google s2 favicons and DuckDuckGo ip3) for the normalized domain, or an empty list if the input is empty.
        """
        normalized_domain = domain.strip().lower()
        if not normalized_domain:
            return []
        return [
            f"https://www.google.com/s2/favicons?sz=128&domain={quote(normalized_domain, safe='')}",
            f"https://icons.duckduckgo.com/ip3/{quote(normalized_domain, safe='')}.ico",
        ]

    def _persist_candidate_logo(self, candidate: dict, ticker: str) -> Optional[str]:
        """
        Persist a logo for a Brandfetch candidate by downloading its provided icon or domain favicon fallbacks.
        
        Parameters:
            candidate (dict): Candidate data from Brandfetch. Expected keys:
                - 'icon' (optional): URL to the candidate's icon.
                - 'domain' (optional): Domain used to generate favicon fallback URLs.
            ticker (str): Ticker symbol used to derive deterministic local asset filenames.
        
        Returns:
            Optional[str]: Public path to the stored logo asset (e.g. "/static/logos/...") if a download and store succeeded, `None` otherwise.
        """
        icon_url = candidate.get('icon') if isinstance(candidate, dict) else None
        domain = str(candidate.get('domain') or '').strip() if isinstance(candidate, dict) else ''

        if isinstance(icon_url, str):
            persisted = self._download_logo_to_local(icon_url, ticker)
            if persisted:
                return persisted

        for fallback_url in self._domain_favicon_candidates(domain):
            persisted = self._download_logo_to_local(fallback_url, ticker)
            if persisted:
                return persisted

        return None

    def should_refresh_logo(self, value: Optional[str]) -> bool:
        """
        Determine whether a logo value requires refreshing (when it is missing or not a local logo path).
        
        Parameters:
            value (Optional[str]): Current logo value; may be a local public path (e.g., "/static/logos/..."), a remote URL, or None.
        
        Returns:
            True if the logo should be refreshed, False otherwise.
        """
        if not value:
            return True
        if not self._is_local_logo_url(value):
            return True
        local_path = os.path.join(LOGO_DIR, value.replace('/static/logos/', '', 1))
        return not os.path.exists(local_path)

    def _discard_cached_logo(self, ticker_upper: str, cache_file: str) -> None:
        _LOGO_CACHE.pop(ticker_upper, None)
        filepath = _resolve_cache_path(cache_file)
        try:
            if os.path.exists(filepath):
                os.remove(filepath)
        except OSError as exc:
            logger.warning("Failed to discard stale logo cache for %s: %s", ticker_upper, exc)

    def _root_domain_token(self, domain: str) -> str:
        """
        Return a concise root-domain token extracted from a domain-like string.
        
        Chooses an identifying label such that common two-part TLDs (e.g., "example.com") yield the second-level label ("example") and recognized multi-label public suffixes (e.g., "example.co.uk") yield the third-from-last label; returns the first label for single-label hosts and an empty string for empty or invalid input.
        
        Parameters:
            domain (str): A domain, hostname, or domain-like string (may include a path or port).
        
        Returns:
            str: The root domain token (e.g., "example" for "https://example.com/path" or "example" for "example.co.uk"), or an empty string if none can be determined.
        """
        normalized = domain.lower().strip()
        if not normalized:
            return ""

        parsed = urlparse(normalized if "://" in normalized else f"//{normalized}")
        host = (parsed.netloc or parsed.path).split("/", 1)[0]
        host = host.rsplit("@", 1)[-1].split(":", 1)[0]
        parts = [part for part in host.split(".") if part]
        if not parts:
            return ""
        multi_label_suffixes = {
            "co.uk",
            "gov.uk",
            "ac.uk",
            "org.uk",
            "com.au",
            "net.au",
            "org.au",
            "co.nz",
            "com.br",
            "com.mx",
            "co.jp",
            "com.sg",
        }
        if len(parts) >= 3 and ".".join(parts[-2:]) in multi_label_suffixes:
            return parts[-3]
        if len(parts) >= 2 and parts[-1] in {"com", "net", "org", "io", "co", "de", "se", "uk", "eu", "ca", "fr", "br", "in", "au", "nz", "jp", "sg", "mx"}:
            return parts[-2]
        if len(parts) >= 2:
            return parts[-2]
        return parts[0]

    def _extract_domain_from_url(self, value: str) -> str:
        """
        Extract the hostname/domain from a URL or bare host string.
        
        Parameters:
            value (str): URL or host-like value such as "https://example.com/path" or "example.com".
        
        Returns:
            str: The extracted lowercase host/domain, or an empty string for falsy input. For example, "https://example.com/path" becomes "example.com".
        """
        if not value:
            return ""
        parsed = urlparse(value if "://" in value else f"https://{value}")
        host = (parsed.netloc or parsed.path).strip().lower()
        return host.split("/", 1)[0].rsplit("@", 1)[-1].split(":", 1)[0]

    def _looks_like_domain(self, value: str) -> bool:
        """
        Determine whether a string resembles a bare domain/host suitable for favicon fallback.

        Parameters:
            value (str): Candidate string to inspect.

        Returns:
            bool: True when the value resolves to a host containing a dot and no spaces, False otherwise.
        """
        if not value or ' ' in value.strip():
            return False
        host = self._extract_domain_from_url(value)
        return bool(host and '.' in host)

    def _normalize_text(self, value: str) -> str:
        """
        Normalize a company name or search query for tokenization and matching.
        
        Converts to lowercase, replaces non-alphanumeric characters with spaces, removes common corporate suffixes and filler words (e.g., "corporation", "inc", "ltd", "holding(s)", "group", "ab", "ag", "nv", "se", "the", "company"), collapses consecutive whitespace, and trims leading/trailing spaces.
        
        Parameters:
            value (str): Raw company name or search query.
        
        Returns:
            str: The cleaned, normalized string suitable for token splitting.
        """
        normalized = value.lower()
        normalized = re.sub(r"[^a-z0-9\s]", " ", normalized)
        normalized = re.sub(r"\b(corporation|corp|inc|ltd|plc|holding|holdings|group|ab|ag|nv|se|the|company)\b", " ", normalized)
        normalized = re.sub(r"\s+", " ", normalized).strip()
        return normalized

    def _token_set(self, value: str) -> set[str]:
        """
        Extracts a set of unique tokens (3 or more characters) from the normalized form of the input text.
        
        Parameters:
            value (str): Text to normalize and tokenize (e.g., company name, ticker, or query).
        
        Returns:
            set[str]: Unique tokens produced from the normalized text where each token has length >= 3.
        """
        normalized = self._normalize_text(value)
        return {token for token in normalized.split(" ") if len(token) >= 3}

    def _normalize_company_query(self, value: str) -> str:
        """
        Normalize a company search query before candidate matching.
        
        Removes parenthetical content, strips abbreviations such as "ser." and "class" when followed by a single letter (case-insensitive), replaces commas with spaces, and delegates final cleanup to `_normalize_text`.
        
        Parameters:
            value (str): Raw company query text to normalize.
        
        Returns:
            str: Normalized query string suitable for matching.
        """
        cleaned = re.sub(r"\(.*?\)", "", value)
        cleaned = re.sub(r"\bser\.?\s+[A-Za-z]\b", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\bclass\s+[A-Za-z]\b", "", cleaned, flags=re.IGNORECASE)
        cleaned = cleaned.replace(',', ' ')
        return self._normalize_text(cleaned)

    def _is_confident_match(
        self,
        candidate: dict,
        ticker: str,
        company_name: Optional[str],
        query: str,
    ) -> bool:
        """
        Determine whether a Brandfetch candidate confidently matches the provided ticker, company name, or query.
        
        Evaluates the candidate's name and domain against expected tokens derived from the ticker, company_name, or query and considers the candidate's verification flag and qualityScore when deciding confidence.
        
        Parameters:
            candidate (dict): Brandfetch result object (expected keys include 'name', 'domain', 'verified', 'qualityScore').
            ticker (str): Ticker symbol being resolved (used to derive expected tokens).
            company_name (Optional[str]): Known company name to strengthen matching; may be None.
            query (str): The search query that produced the candidate; used as a fallback for expected tokens.
        
        Returns:
            True if the candidate is considered a confident match, False otherwise.
        """
        candidate_name = str(candidate.get('name') or '')
        candidate_domain = str(candidate.get('domain') or '')
        candidate_host = self._extract_domain_from_url(candidate_domain)
        verified = bool(candidate.get('verified'))
        quality_score = float(candidate.get('qualityScore') or 0)
        candidate_name_normalized = self._normalize_text(candidate_name)
        candidate_domain_root = self._normalize_text(self._root_domain_token(candidate_host))
        query_normalized_text = query.strip().lower()
        ticker_normalized_text = ticker.strip().lower()
        looks_like_dotted_ticker = bool(re.fullmatch(r"[a-z]{1,5}\.[a-z]{1,3}", query_normalized_text))
        looks_like_hostname = bool(re.fullmatch(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+", query.strip()))
        curated_host = (
            self._extract_domain_from_url(query)
            if looks_like_hostname and query_normalized_text != ticker_normalized_text and not looks_like_dotted_ticker
            else ''
        )
        curated_domain_root = self._normalize_text(self._root_domain_token(curated_host))
        query_normalized = curated_domain_root or self._normalize_text(query)

        expected_tokens: set[str] = set()
        expected_name_normalized = self._normalize_text(company_name or '')
        if company_name and company_name.strip():
            expected_tokens |= self._token_set(company_name)

        ticker_base = ticker.upper().split('.', 1)[0].split('-', 1)[0]
        valid_ticker = bool(ticker_base and ticker_base.isalpha() and len(ticker_base) >= 3)
        ticker_token = ticker_base.lower() if valid_ticker else ''
        if ticker_token:
            expected_tokens.add(ticker_token)

        if not expected_tokens:
            expected_tokens |= self._token_set(query)

        candidate_tokens = self._token_set(candidate_name)
        domain_tokens = self._token_set(candidate_domain.replace('.', ' '))
        matched = expected_tokens.intersection(candidate_tokens.union(domain_tokens))
        match_ratio = (len(matched) / len(expected_tokens)) if expected_tokens else 0
        exact_identity_match = any(
            token
            for token in {
                expected_name_normalized,
                query_normalized,
                ticker_token,
            }
            if token and token in {candidate_name_normalized, candidate_domain_root}
        )

        if len(expected_tokens) <= 1:
            if curated_host and candidate_host == curated_host and quality_score >= 0.5:
                return True
            if verified and quality_score >= 0.99 and (
                exact_identity_match
                or (curated_host and candidate_host == curated_host)
            ):
                return True
            return False

        if curated_host and candidate_host == curated_host and quality_score >= 0.5:
            return True

        if exact_identity_match and quality_score >= 0.5:
            return True

        if match_ratio >= 0.6:
            return True

        if verified and quality_score >= 0.95 and match_ratio >= 0.4:
            return True

        return False

    def _build_query_candidates(self, ticker: str, company_name: Optional[str]) -> list[str]:
        """
        Builds an ordered list of search query candidates derived from a ticker and an optional company name.
        
        Generates prioritized search strings from the provided company name (original and cleaned variants that remove common corporate suffixes and parenthetical content) and from the ticker (uppercased form, base before a dot, and root before a hyphen when appropriate). Preserves the original ordering of candidates and removes duplicates while keeping the first occurrence.
        
        Parameters:
            ticker (str): Stock ticker symbol used to derive ticker-based candidates.
            company_name (Optional[str]): Optional company name used to derive name-based candidates.
        
        Returns:
            list[str]: Ordered, unique list of candidate query strings (highest-priority first).
        """
        candidates: list[str] = list(_CURATED_LOGO_QUERIES.get(ticker.upper().strip(), []))

        if company_name and company_name.strip():
            clean_name = company_name.strip()
            candidates.append(clean_name)

            normalized_clean = self._normalize_company_query(clean_name)
            if normalized_clean and normalized_clean != clean_name:
                candidates.append(normalized_clean)

            ab_split = re.split(r"\bAB\b", clean_name, maxsplit=1, flags=re.IGNORECASE)
            if len(ab_split) > 1:
                for piece in ab_split:
                    normalized_piece = self._normalize_company_query(piece)
                    if normalized_piece and normalized_piece != normalized_clean:
                        candidates.append(normalized_piece)

        ticker_upper = ticker.upper().strip()
        if ticker_upper:
            ticker_base = ticker_upper.split('.', 1)[0]
            if ticker_base and ticker_base != ticker_upper:
                candidates.append(ticker_base)

            candidates.append(ticker_upper)

            if (not company_name or not company_name.strip()) and '-' in ticker_base:
                ticker_root = ticker_base.split('-', 1)[0]
                if ticker_root:
                    candidates.append(ticker_root)

        unique_candidates: list[str] = []
        seen: set[str] = set()
        for candidate in candidates:
            if candidate and candidate not in seen:
                seen.add(candidate)
                unique_candidates.append(candidate)

        return unique_candidates

    def _search_logo(self, query: str, ticker: str, company_name: Optional[str]) -> Optional[dict]:
        """
        Search Brandfetch for candidates and return the first candidate judged to be a confident match.
        
        Parameters:
            query (str): Search query to send to Brandfetch; if empty, no request is made.
            ticker (str): Uppercase stock ticker used to evaluate candidate match confidence.
            company_name (Optional[str]): Company name used to derive expected tokens for matching; may be None.
        
        Returns:
            Optional[dict]: The first Brandfetch candidate dictionary judged a confident match, or `None` if no suitable candidate is found.
        """
        if not query:
            return None

        session = _get_session()
        url = f"https://api.brandfetch.io/v2/search/{quote(query, safe='')}"

        try:
            response = session.get(url, timeout=10)
            if response.status_code != 200:
                return None

            data = response.json()
            if not isinstance(data, list) or not data:
                return None

            for candidate in data:
                if isinstance(candidate, dict) and self._is_confident_match(candidate, ticker, company_name, query):
                    return candidate
        except Exception as exc:
            logger.warning(f"Brandfetch search failed for '{query}': {exc}")

        return None

    def _get_finnhub_logo(self, ticker: str, force_refresh: bool = False) -> Optional[str]:
        if force_refresh:
            finnhub_service.clear_cache(ticker)
        profile = finnhub_service.get_company_profile(ticker)
        if not isinstance(profile, dict):
            return None

        website_domain = self._extract_domain_from_url(str(profile.get('website') or ''))
        candidate = {
            'icon': profile.get('logo'),
            'domain': website_domain or None,
        }
        return self._persist_candidate_logo(candidate, ticker)

    def get_logo_url_for_ticker(
        self,
        ticker: str,
        company_name: Optional[str] = None,
        force_refresh: bool = False,
        existing_logo: Optional[str] = None,
    ) -> Optional[str]:
        """
        Resolve a logo URL for a given stock ticker, consulting in-memory and on-disk caches and falling back to Brandfetch search when needed.
        
        Parameters:
            ticker (str): Stock ticker symbol (case-insensitive).
            company_name (Optional[str]): Optional company name to improve search relevance.
            force_refresh (bool): If True, bypass in-memory and file caches and perform a fresh search.
            existing_logo (Optional[str]): An existing logo URL or local path; if a local path is provided and refresh is not forced it will be returned as-is; if a remote URL is provided the service will attempt to download and persist it locally.
        
        Returns:
            Optional[str]: The resolved public logo path (local "/static/logos/..." path) if found or persisted, or `None` if no suitable logo could be resolved.
        """
        ticker_upper = ticker.strip().upper()
        cache_file = _safe_logo_cache_filename(ticker_upper)

        if existing_logo and self._is_legacy_remote_logo_url(existing_logo):
            force_refresh = True

        if existing_logo and self._is_local_logo_url(existing_logo) and not force_refresh and not self.should_refresh_logo(existing_logo):
            return existing_logo
        if existing_logo and self._is_local_logo_url(existing_logo) and self.should_refresh_logo(existing_logo):
            existing_logo = None
            self._discard_cached_logo(ticker_upper, cache_file)

        if existing_logo and self._is_remote_logo_url(existing_logo):
            try:
                persisted_existing_logo = self._download_logo_to_local(existing_logo, ticker_upper)
            except LogoDownloadTransientError:
                return existing_logo
            if persisted_existing_logo:
                _LOGO_CACHE[ticker_upper] = (persisted_existing_logo, datetime.now().timestamp())
                _save_file_cache(cache_file, persisted_existing_logo)
                return persisted_existing_logo

        if not force_refresh and ticker_upper in _LOGO_CACHE:
            cached_logo, timestamp = _LOGO_CACHE[ticker_upper]
            if datetime.now().timestamp() - timestamp < _LOGO_CACHE_TTL:
                if cached_logo is None:
                    return cached_logo
                if self._is_local_logo_url(cached_logo) and not self.should_refresh_logo(cached_logo):
                    return cached_logo
                if self._is_local_logo_url(cached_logo):
                    self._discard_cached_logo(ticker_upper, cache_file)

        if not force_refresh:
            cache_hit, cached_logo = _load_file_cache(cache_file)
            if cache_hit:
                if cached_logo is None:
                    _LOGO_CACHE[ticker_upper] = (cached_logo, datetime.now().timestamp())
                    return cached_logo
                if self._is_local_logo_url(cached_logo) and not self.should_refresh_logo(cached_logo):
                    _LOGO_CACHE[ticker_upper] = (cached_logo, datetime.now().timestamp())
                    return cached_logo
                if self._is_local_logo_url(cached_logo):
                    self._discard_cached_logo(ticker_upper, cache_file)

        if force_refresh:
            _LOGO_CACHE.pop(ticker_upper, None)
            filepath = _resolve_cache_path(cache_file)
            try:
                if os.path.exists(filepath):
                    os.remove(filepath)
            except OSError as exc:
                logger.warning("Failed to clear stale logo cache for %s: %s", ticker_upper, exc)

        try:
            logo_url = self._get_finnhub_logo(ticker_upper, force_refresh=force_refresh)
        except LogoDownloadTransientError:
            return existing_logo if existing_logo and not self.should_refresh_logo(existing_logo) else None
        if logo_url:
            _LOGO_CACHE[ticker_upper] = (logo_url, datetime.now().timestamp())
            _save_file_cache(cache_file, logo_url)
            return logo_url

        candidates = self._build_query_candidates(ticker_upper, company_name)

        logo_url = None
        for query in candidates:
            if self._looks_like_domain(query):
                try:
                    logo_url = self._persist_candidate_logo(
                        {'domain': self._extract_domain_from_url(query)},
                        ticker_upper,
                    )
                except LogoDownloadTransientError:
                    return existing_logo if existing_logo and not self.should_refresh_logo(existing_logo) else None
                if logo_url:
                    break
            candidate = self._search_logo(query, ticker_upper, company_name)
            try:
                logo_url = self._persist_candidate_logo(candidate, ticker_upper) if candidate else None
            except LogoDownloadTransientError:
                return existing_logo if existing_logo and not self.should_refresh_logo(existing_logo) else None
            if logo_url:
                break

        _LOGO_CACHE[ticker_upper] = (logo_url, datetime.now().timestamp())
        _save_file_cache(cache_file, logo_url)
        return logo_url


brandfetch_service = BrandfetchService()
