"""Brandfetch logo service.

This module resolves logo URLs using Brandfetch search endpoint and caches
the resulting icon URL by ticker.
"""

import json
import logging
import os
import re
import hashlib
import mimetypes
from datetime import datetime
from typing import Optional
from urllib.parse import quote, urlparse

import requests

logger = logging.getLogger(__name__)

CACHE_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'cache')
LOGO_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'static', 'logos')
os.makedirs(CACHE_DIR, exist_ok=True)
os.makedirs(LOGO_DIR, exist_ok=True)

_LOGO_CACHE_TTL = 86400
_LOGO_CACHE: dict[str, tuple[Optional[str], float]] = {}
_CURATED_LOGO_QUERIES: dict[str, list[str]] = {
    "VOLV-B.ST": ["volvogroup.com", "Volvo Group"],
}

_session: Optional[requests.Session] = None
_ALLOWED_REMOTE_LOGO_HOSTS = {
    'cdn.brandfetch.io',
    'logo.clearbit.com',
    'www.google.com',
    'icons.duckduckgo.com',
}
_LEGACY_BRANDFETCH_HOSTS = {
    'cdn.brandfetch.io',
}


def _resolve_cache_path(filename: str) -> str:
    """
    Resolve a filename to an absolute path confined inside the module cache directory.
    
    Parameters:
        filename (str): A cache filename or relative path; may include subdirectories.
    
    Returns:
        str: Absolute path to the resolved cache file inside the module cache directory.
    
    Raises:
        ValueError: If the resolved path is outside the configured cache directory.
    """
    cache_dir_abs = os.path.abspath(CACHE_DIR)
    filepath = os.path.abspath(os.path.join(cache_dir_abs, filename))
    if filepath != cache_dir_abs and not filepath.startswith(f"{cache_dir_abs}{os.sep}"):
        raise ValueError(f"Invalid cache path outside cache directory: {filename}")
    return filepath


def _safe_logo_cache_filename(ticker_upper: str) -> str:
    """
    Return a deterministic, filesystem-safe cache filename for a ticker.
    
    Parameters:
        ticker_upper (str): Uppercased ticker string used to derive the filename.
    
    Returns:
        filename (str): Versioned JSON filename derived from the SHA-256 digest (first 24 hex chars) of the ticker, e.g. "brandfetch_logo_v2_<digest>.json".
    """
    digest = hashlib.sha256(ticker_upper.encode('utf-8')).hexdigest()[:24]
    return f"brandfetch_logo_v2_{digest}.json"


def _safe_logo_asset_filename(ticker_upper: str, source: str, extension: str) -> str:
    digest = hashlib.sha256(f"{ticker_upper}:{source}".encode('utf-8')).hexdigest()[:24]
    sanitized_extension = extension if extension.startswith('.') else f'.{extension}'
    return f"logo_{digest}{sanitized_extension}"


def _get_session() -> requests.Session:
    """
    Provide a configured, shared requests Session for HTTP requests.
    
    Returns:
        requests.Session: The module-level singleton Session with default headers set (`User-Agent`, `Accept`, `Accept-Language`, `Connection`).
    """
    global _session
    if _session is None:
        _session = requests.Session()
        _session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.9',
            'Connection': 'keep-alive',
        })
    return _session


def _load_file_cache(filename: str) -> tuple[bool, Optional[str]]:
    """
    Load a cached logo value from a file if the cache entry exists and is still valid.
    
    Attempts to resolve and read the JSON cache file for `filename`. Validates the entry's TTL using the file's `timestamp` and `ttl` (falls back to the module default TTL). Recognizes an explicit cached null via the `is_null` flag.
    
    Parameters:
        filename (str): Cache filename (relative name previously generated by the module).
    
    Returns:
        tuple[bool, Optional[str]]: A pair where the first element is `True` if a valid cache entry was found (including an explicit null), `False` otherwise. The second element is the cached string value when present, or `None` if the cache recorded a null or no valid entry exists.
    
    Notes:
        On error (file read/parse/validation), the function logs a warning and returns `(False, None)`.
    """
    try:
        filepath = _resolve_cache_path(filename)
        if not os.path.exists(filepath):
            return False, None
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        if datetime.now().timestamp() - data.get('timestamp', 0) >= data.get('ttl', _LOGO_CACHE_TTL):
            return False, None

        if data.get('is_null') is True:
            return True, None

        if 'value' in data:
            return True, data.get('value')
    except Exception as exc:
        logger.warning(f"Failed to load cache file {filename}: {exc}")

    return False, None


def _save_file_cache(filename: str, value: Optional[str], ttl: int = _LOGO_CACHE_TTL) -> None:
    """
    Write a cache file for a ticker-resolved logo value.
    
    Creates or overwrites the cache JSON file identified by `filename` (resolved into the module cache directory) and records `value` (string URL or `None`), an `is_null` flag, the current timestamp, and the `ttl` (time-to-live in seconds). On failure the function logs a warning and returns without raising.
    
    Parameters:
        filename (str): Cache filename (resolved to the module cache directory).
        value (Optional[str]): Cached value to store; use `None` to record a null result.
        ttl (int): Time-to-live for the cached entry in seconds.
    """
    try:
        filepath = _resolve_cache_path(filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump({
                'value': value,
                'is_null': value is None,
                'timestamp': datetime.now().timestamp(),
                'ttl': ttl,
            }, f)
    except Exception as exc:
        logger.warning(f"Failed to save cache file {filename}: {exc}")


class BrandfetchService:
    def _is_local_logo_url(self, value: Optional[str]) -> bool:
        return bool(value and value.startswith('/static/logos/'))

    def _is_remote_logo_url(self, value: Optional[str]) -> bool:
        if not value:
            return False
        parsed = urlparse(value)
        return parsed.scheme in {'http', 'https'} and bool(parsed.netloc)

    def _is_allowed_remote_logo_url(self, value: str) -> bool:
        parsed = urlparse(value)
        return parsed.scheme in {'http', 'https'} and parsed.netloc.lower() in _ALLOWED_REMOTE_LOGO_HOSTS

    def _is_legacy_remote_logo_url(self, value: str) -> bool:
        if not value:
            return False
        parsed = urlparse(value)
        return parsed.scheme in {'http', 'https'} and parsed.netloc.lower() in _LEGACY_BRANDFETCH_HOSTS

    def _logo_public_path(self, filename: str) -> str:
        return f"/static/logos/{filename}"

    def _download_logo_to_local(self, logo_url: str, ticker: str) -> Optional[str]:
        if not self._is_allowed_remote_logo_url(logo_url):
            return None

        session = _get_session()
        try:
            response = session.get(logo_url, timeout=10)
            if response.status_code != 200:
                return None

            content_type = (response.headers.get('Content-Type') or '').split(';', 1)[0].strip().lower()
            if not content_type.startswith('image/'):
                return None

            extension = mimetypes.guess_extension(content_type) or os.path.splitext(urlparse(logo_url).path)[1] or '.png'
            if extension == '.jpe':
                extension = '.jpg'

            filename = _safe_logo_asset_filename(ticker, logo_url, extension)
            filepath = os.path.join(LOGO_DIR, filename)
            with open(filepath, 'wb') as f:
                f.write(response.content)

            return self._logo_public_path(filename)
        except Exception as exc:
            logger.warning("Failed to persist logo for %s from %s: %s", ticker, logo_url, exc)
            return None

    def _domain_favicon_candidates(self, domain: str) -> list[str]:
        normalized_domain = domain.strip().lower()
        if not normalized_domain:
            return []
        return [
            f"https://www.google.com/s2/favicons?sz=128&domain={quote(normalized_domain, safe='')}",
            f"https://icons.duckduckgo.com/ip3/{quote(normalized_domain, safe='')}.ico",
        ]

    def _persist_candidate_logo(self, candidate: dict, ticker: str) -> Optional[str]:
        icon_url = candidate.get('icon') if isinstance(candidate, dict) else None
        domain = str(candidate.get('domain') or '').strip() if isinstance(candidate, dict) else ''

        if isinstance(icon_url, str):
            persisted = self._download_logo_to_local(icon_url, ticker)
            if persisted:
                return persisted

        for fallback_url in self._domain_favicon_candidates(domain):
            persisted = self._download_logo_to_local(fallback_url, ticker)
            if persisted:
                return persisted

        return None

    def should_refresh_logo(self, value: Optional[str]) -> bool:
        return not value or not self._is_local_logo_url(value)

    def _root_domain_token(self, domain: str) -> str:
        """
        Derives a root domain token from a domain-like string.
        
        Strips any path or port, lowercases the input, and returns a concise identifier for the domain:
        - If the hostname ends with a recognized top-level domain (e.g., "com", "net", "io", "se"), returns the second-level label (e.g., "example" for "example.com").
        - Otherwise returns the first hostname label.
        Returns an empty string for empty or invalid input.
        
        Parameters:
            domain (str): A domain, hostname, or domain-like string (may include path or port).
        
        Returns:
            str: The root domain token, or an empty string if none can be determined.
        """
        normalized = domain.lower().strip()
        if not normalized:
            return ""

        parsed = urlparse(normalized if "://" in normalized else f"//{normalized}")
        host = (parsed.netloc or parsed.path).split("/", 1)[0]
        host = host.rsplit("@", 1)[-1].split(":", 1)[0]
        parts = [part for part in host.split(".") if part]
        if not parts:
            return ""
        multi_label_suffixes = {
            "co.uk",
            "gov.uk",
            "ac.uk",
            "org.uk",
            "com.au",
            "net.au",
            "org.au",
            "co.nz",
            "com.br",
            "com.mx",
            "co.jp",
            "com.sg",
        }
        if len(parts) >= 3 and ".".join(parts[-2:]) in multi_label_suffixes:
            return parts[-3]
        if len(parts) >= 2 and parts[-1] in {"com", "net", "org", "io", "co", "de", "se", "uk", "eu", "ca", "fr", "br", "in", "au", "nz", "jp", "sg", "mx"}:
            return parts[-2]
        if len(parts) >= 2:
            return parts[-2]
        return parts[0]

    def _normalize_text(self, value: str) -> str:
        """
        Normalize a company name or search query for tokenization and matching.
        
        Converts to lowercase, replaces non-alphanumeric characters with spaces, removes common corporate suffixes and filler words (e.g., "corporation", "inc", "ltd", "holding(s)", "group", "ab", "ag", "nv", "se", "the", "company"), collapses consecutive whitespace, and trims leading/trailing spaces.
        
        Parameters:
            value (str): Raw company name or search query.
        
        Returns:
            str: The cleaned, normalized string suitable for token splitting.
        """
        normalized = value.lower()
        normalized = re.sub(r"[^a-z0-9\s]", " ", normalized)
        normalized = re.sub(r"\b(corporation|corp|inc|ltd|plc|holding|holdings|group|ab|ag|nv|se|the|company)\b", " ", normalized)
        normalized = re.sub(r"\s+", " ", normalized).strip()
        return normalized

    def _token_set(self, value: str) -> set[str]:
        """
        Extracts a set of unique tokens (3 or more characters) from the normalized form of the input text.
        
        Parameters:
            value (str): Text to normalize and tokenize (e.g., company name, ticker, or query).
        
        Returns:
            set[str]: Unique tokens produced from the normalized text where each token has length >= 3.
        """
        normalized = self._normalize_text(value)
        return {token for token in normalized.split(" ") if len(token) >= 3}

    def _normalize_company_query(self, value: str) -> str:
        """
        Normalize a company search query before candidate matching.
        
        Removes parenthetical content, strips abbreviations such as "ser." and "class" when followed by a single letter (case-insensitive), replaces commas with spaces, and delegates final cleanup to `_normalize_text`.
        
        Parameters:
            value (str): Raw company query text to normalize.
        
        Returns:
            str: Normalized query string suitable for matching.
        """
        cleaned = re.sub(r"\(.*?\)", "", value)
        cleaned = re.sub(r"\bser\.?\s+[A-Za-z]\b", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\bclass\s+[A-Za-z]\b", "", cleaned, flags=re.IGNORECASE)
        cleaned = cleaned.replace(',', ' ')
        return self._normalize_text(cleaned)

    def _is_confident_match(
        self,
        candidate: dict,
        ticker: str,
        company_name: Optional[str],
        query: str,
    ) -> bool:
        """
        Determine whether a Brandfetch candidate confidently matches the provided ticker, company name, or query.
        
        Evaluates the candidate's name and domain against expected tokens derived from the ticker, company_name, or query and considers the candidate's verification flag and qualityScore when deciding confidence.
        
        Parameters:
            candidate (dict): Brandfetch result object (expected keys include 'name', 'domain', 'verified', 'qualityScore').
            ticker (str): Ticker symbol being resolved (used to derive expected tokens).
            company_name (Optional[str]): Known company name to strengthen matching; may be None.
            query (str): The search query that produced the candidate; used as a fallback for expected tokens.
        
        Returns:
            True if the candidate is considered a confident match, False otherwise.
        """
        candidate_name = str(candidate.get('name') or '')
        candidate_domain = str(candidate.get('domain') or '')
        verified = bool(candidate.get('verified'))
        quality_score = float(candidate.get('qualityScore') or 0)
        candidate_name_normalized = self._normalize_text(candidate_name)
        candidate_domain_root = self._normalize_text(self._root_domain_token(candidate_domain))
        query_normalized_text = query.strip().lower()
        ticker_normalized_text = ticker.strip().lower()
        looks_like_dotted_ticker = bool(re.fullmatch(r"[a-z]{1,5}\.[a-z]{1,3}", query_normalized_text))
        looks_like_hostname = bool(re.fullmatch(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+", query.strip()))
        curated_domain_root = (
            self._normalize_text(self._root_domain_token(query))
            if looks_like_hostname and query_normalized_text != ticker_normalized_text and not looks_like_dotted_ticker
            else ''
        )
        query_normalized = curated_domain_root or self._normalize_text(query)

        expected_tokens: set[str] = set()
        expected_name_normalized = self._normalize_text(company_name or '')
        if company_name and company_name.strip():
            expected_tokens |= self._token_set(company_name)

        ticker_base = ticker.upper().split('.', 1)[0].split('-', 1)[0]
        valid_ticker = bool(ticker_base and ticker_base.isalpha() and len(ticker_base) >= 3)
        ticker_token = ticker_base.lower() if valid_ticker else ''
        if ticker_token:
            expected_tokens.add(ticker_token)

        if not expected_tokens:
            expected_tokens |= self._token_set(query)

        candidate_tokens = self._token_set(candidate_name)
        domain_tokens = self._token_set(candidate_domain.replace('.', ' '))
        matched = expected_tokens.intersection(candidate_tokens.union(domain_tokens))
        match_ratio = (len(matched) / len(expected_tokens)) if expected_tokens else 0
        exact_identity_match = any(
            token
            for token in {
                expected_name_normalized,
                query_normalized,
                ticker_token,
            }
            if token and token in {candidate_name_normalized, candidate_domain_root}
        )

        if len(expected_tokens) <= 1:
            if verified and quality_score >= 0.99 and (
                exact_identity_match
                or (curated_domain_root and candidate_domain_root == curated_domain_root)
            ):
                return True
            return False

        if curated_domain_root and candidate_domain_root == curated_domain_root and quality_score >= 0.5:
            return True

        if exact_identity_match and quality_score >= 0.5:
            return True

        if match_ratio >= 0.6:
            return True

        if verified and quality_score >= 0.95 and match_ratio >= 0.4:
            return True

        return False

    def _build_query_candidates(self, ticker: str, company_name: Optional[str]) -> list[str]:
        """
        Builds an ordered list of search query candidates derived from a ticker and an optional company name.
        
        Generates prioritized search strings from the provided company name (original and cleaned variants that remove common corporate suffixes and parenthetical content) and from the ticker (uppercased form, base before a dot, and root before a hyphen when appropriate). Preserves the original ordering of candidates and removes duplicates while keeping the first occurrence.
        
        Parameters:
            ticker (str): Stock ticker symbol used to derive ticker-based candidates.
            company_name (Optional[str]): Optional company name used to derive name-based candidates.
        
        Returns:
            list[str]: Ordered, unique list of candidate query strings (highest-priority first).
        """
        candidates: list[str] = list(_CURATED_LOGO_QUERIES.get(ticker.upper().strip(), []))

        if company_name and company_name.strip():
            clean_name = company_name.strip()
            candidates.append(clean_name)

            normalized_clean = self._normalize_company_query(clean_name)
            if normalized_clean and normalized_clean != clean_name:
                candidates.append(normalized_clean)

            ab_split = re.split(r"\bAB\b", clean_name, maxsplit=1, flags=re.IGNORECASE)
            if len(ab_split) > 1:
                for piece in ab_split:
                    normalized_piece = self._normalize_company_query(piece)
                    if normalized_piece and normalized_piece != normalized_clean:
                        candidates.append(normalized_piece)

        ticker_upper = ticker.upper().strip()
        if ticker_upper:
            ticker_base = ticker_upper.split('.', 1)[0]
            if ticker_base and ticker_base != ticker_upper:
                candidates.append(ticker_base)

            candidates.append(ticker_upper)

            if (not company_name or not company_name.strip()) and '-' in ticker_base:
                ticker_root = ticker_base.split('-', 1)[0]
                if ticker_root:
                    candidates.append(ticker_root)

        unique_candidates: list[str] = []
        seen: set[str] = set()
        for candidate in candidates:
            if candidate and candidate not in seen:
                seen.add(candidate)
                unique_candidates.append(candidate)

        return unique_candidates

    def _search_logo(self, query: str, ticker: str, company_name: Optional[str]) -> Optional[dict]:
        """
        Searches Brandfetch for a logo matching the provided query and returns the first confidently matched icon URL.
        
        Parameters:
            query (str): Search query string to send to Brandfetch; if empty, no search is performed.
            ticker (str): Uppercase stock ticker used to evaluate candidate match confidence.
            company_name (Optional[str]): Company name used to build expected tokens for matching; may be None.
        
        Returns:
            Optional[dict]: The first Brandfetch candidate judged to be a confident match, or `None` if no suitable logo is found.
        """
        if not query:
            return None

        session = _get_session()
        url = f"https://api.brandfetch.io/v2/search/{quote(query, safe='')}"

        try:
            response = session.get(url, timeout=10)
            if response.status_code != 200:
                return None

            data = response.json()
            if not isinstance(data, list) or not data:
                return None

            for candidate in data:
                if isinstance(candidate, dict) and self._is_confident_match(candidate, ticker, company_name, query):
                    return candidate
        except Exception as exc:
            logger.warning(f"Brandfetch search failed for '{query}': {exc}")

        return None

    def get_logo_url_for_ticker(
        self,
        ticker: str,
        company_name: Optional[str] = None,
        force_refresh: bool = False,
        existing_logo: Optional[str] = None,
    ) -> Optional[str]:
        """
        Resolve a logo URL for a given stock ticker, using in-memory and file-based caches and falling back to Brandfetch search when needed.
        
        Parameters:
            ticker (str): Stock ticker symbol (case-insensitive).
            company_name (Optional[str]): Optional company name to improve search relevance.
            force_refresh (bool): If True, bypass both in-memory and file caches and perform a fresh search.
        
        Returns:
            Optional[str]: The resolved logo URL if found, `None` otherwise.
        """
        ticker_upper = ticker.strip().upper()
        cache_file = _safe_logo_cache_filename(ticker_upper)

        if existing_logo and self._is_legacy_remote_logo_url(existing_logo):
            force_refresh = True

        if existing_logo and self._is_local_logo_url(existing_logo) and not force_refresh:
            return existing_logo

        if existing_logo and self._is_remote_logo_url(existing_logo):
            persisted_existing_logo = self._download_logo_to_local(existing_logo, ticker_upper)
            if persisted_existing_logo:
                _LOGO_CACHE[ticker_upper] = (persisted_existing_logo, datetime.now().timestamp())
                _save_file_cache(cache_file, persisted_existing_logo)
                return persisted_existing_logo

        if not force_refresh and ticker_upper in _LOGO_CACHE:
            cached_logo, timestamp = _LOGO_CACHE[ticker_upper]
            if datetime.now().timestamp() - timestamp < _LOGO_CACHE_TTL:
                if self._is_local_logo_url(cached_logo) or cached_logo is None:
                    return cached_logo

        if not force_refresh:
            cache_hit, cached_logo = _load_file_cache(cache_file)
            if cache_hit:
                if self._is_local_logo_url(cached_logo) or cached_logo is None:
                    _LOGO_CACHE[ticker_upper] = (cached_logo, datetime.now().timestamp())
                    return cached_logo

        if force_refresh:
            _LOGO_CACHE.pop(ticker_upper, None)
            try:
                filepath = _resolve_cache_path(cache_file)
                if os.path.exists(filepath):
                    os.remove(filepath)
            except Exception:
                logger.warning("Failed to clear stale logo cache for %s", ticker_upper)

        candidates = self._build_query_candidates(ticker_upper, company_name)

        logo_url = None
        for query in candidates:
            candidate = self._search_logo(query, ticker_upper, company_name)
            logo_url = self._persist_candidate_logo(candidate, ticker_upper) if candidate else None
            if logo_url:
                break

        _LOGO_CACHE[ticker_upper] = (logo_url, datetime.now().timestamp())
        _save_file_cache(cache_file, logo_url)
        return logo_url


brandfetch_service = BrandfetchService()
